DROP TABLE IF EXISTS outbox;
DROP TABLE IF EXISTS dead_letter_messages;
DROP TABLE IF EXISTS inbox;
DROP TRIGGER IF EXISTS wallet_ledger_immutable ON wallet_ledger;
DROP TRIGGER IF EXISTS wallet_balance_matches_ledger ON wallets;
DROP TRIGGER IF EXISTS ledger_matches_wallet ON wallet_ledger;
DROP TRIGGER IF EXISTS ledger_matches_processed_transaction ON wallet_ledger;
DROP TRIGGER IF EXISTS wager_ledger_terminal_consistency ON wager_transactions;
DROP FUNCTION IF EXISTS check_wallet_ledger_balance();
DROP FUNCTION IF EXISTS validate_committed_ledger_entry();
DROP FUNCTION IF EXISTS check_processed_transaction_ledger();
DROP TABLE IF EXISTS wallet_ledger;
DROP FUNCTION IF EXISTS reject_ledger_mutation();
DROP TRIGGER IF EXISTS wager_transaction_creation ON wager_transactions;
DROP FUNCTION IF EXISTS validate_wager_creation();
DROP TRIGGER IF EXISTS wager_transaction_transition ON wager_transactions;
DROP FUNCTION IF EXISTS protect_wager_transaction();
DROP TABLE IF EXISTS wager_transactions;
DROP TABLE IF EXISTS wallets;